# Generated by Django 4.1.1 on 2022-09-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('phone_combined', models.CharField(blank=True, default='', max_length=255)),
                ('admin_slug', models.CharField(blank=True, default='', max_length=255)),
                ('product_id', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('device_model', models.CharField(blank=True, default='', max_length=255)),
                ('carrier', models.CharField(blank=True, default='', max_length=255)),
                ('quote_new', models.CharField(blank=True, default='', max_length=255)),
                ('quote_working', models.CharField(blank=True, default='', max_length=255)),
                ('quote_broken', models.CharField(blank=True, default='', max_length=255)),
                ('extra_csv_cols', models.TextField()),
                ('device_category', models.CharField(blank=True, choices=[('', ''), ('Smartphone', 'Smartphone'), ('Feature Phone', 'Feature Phone'), ('Connect Device', 'Connect Device'), ('Tablet', 'Tablet'), ('Case', 'Case')], default='', max_length=255)),
                ('requires_managers_approval', models.BooleanField(default=False)),
                ('commission_eligible', models.BooleanField(default=False)),
                ('commission_eligible_empty', models.BooleanField(default=False, editable=False)),
                ('show_on_quote_pricing_tool', models.BooleanField(default=False)),
                ('show_on_sales_order_pricing_tool', models.BooleanField(default=False)),
                ('sales_order_used_b_stock_pricing', models.CharField(blank=True, default='', max_length=255)),
                ('fmv_ftw', models.CharField(blank=True, default='', max_length=255)),
                ('fmv_pgl', models.CharField(blank=True, default='', max_length=255)),
                ('fmv_pbl', models.CharField(blank=True, default='', max_length=255)),
                ('fmv_np', models.CharField(blank=True, default='', max_length=255)),
                ('fmv_pgl_icloud', models.CharField(blank=True, default='', max_length=255)),
                ('fmv_pbl_icloud', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'Catalog Phone',
                'verbose_name_plural': 'Catalog Phones',
                'ordering': ['manufacturer', 'device_name', 'device_model'],
            },
        ),
    ]
