# Generated by Django 4.1.1 on 2022-09-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbwphone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCatalogSOPricing',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gbwphone.phonecatalog',),
        ),
    ]
